# Generated by Django 2.2.1 on 2019-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
