# Generated by Django 2.2.1 on 2019-06-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20190603_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('sports', 'Sports & Fitness'), ('social', 'Social'), ('fun', 'Fun'), ('errands', 'Errands'), ('self_dev', 'Self Development'), ('sleep', 'Sleep/Rest'), ('proc', 'Procrastination')], default='work', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
