# Generated by Django 2.2.1 on 2019-06-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20190604_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('sports', 'Sports & Fitness'), ('social', 'Social'), ('fun', 'Fun'), ('errands', 'Errands'), ('self_dev', 'Self Development'), ('sleep', 'Sleep/Rest'), ('proc', 'Procrastination')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
