# Generated by Django 2.2.1 on 2019-06-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
    ]
