# Generated by Django 2.2.1 on 2019-06-14 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20190614_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 14, 1, 38, 34, 548475, tzinfo=utc)),
        ),
    ]
