# Generated by Django 2.2.1 on 2019-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20190614_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
