# Generated by Django 2.2.1 on 2019-06-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_task_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')]),
        ),
    ]
