# Generated by Django 2.2.1 on 2019-07-01 04:29

import dash.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_auto_20190624_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='rating',
        ),
        migrations.AddField(
            model_name='goal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='expiry',
            field=models.DateField(default=dash.models.set_active_expiry),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_id',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Goal')),
            ],
        ),
    ]
