# Generated by Django 2.2.1 on 2019-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20190701_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_id',
            field=models.IntegerField(),
        ),
    ]
