# Generated by Django 2.2.1 on 2019-07-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_auto_20190701_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_id',
        ),
    ]
