# Generated by Django 2.2.1 on 2019-07-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_remove_task_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_id',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
