# Generated by Django 2.2.1 on 2019-07-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_task_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
