# Generated by Django 2.2.1 on 2019-07-01 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0018_auto_20190701_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='user',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
