# Generated by Django 2.2.1 on 2019-07-03 11:38

import dash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_subtask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(default='PN', max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='expiry',
            field=models.DateField(default=dash.models.set_final_expiry),
        ),
    ]
